set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_C_COMPILER   /opt/homebrew/opt/llvm@18/bin/clang)
set(CMAKE_CXX_COMPILER /opt/homebrew/opt/llvm@18/bin/clang++)
set(CMAKE_AR      /Users/anant/Workspace/ProsperoAI/.deps/native/ps5-payload-sdk/bin/llvm-ar)
set(CMAKE_RANLIB  /Users/anant/Workspace/ProsperoAI/.deps/native/ps5-payload-sdk/bin/llvm-ranlib)
set(CMAKE_C_FLAGS   "-target x86_64-sie-ps5 -isysroot /Users/anant/Workspace/ProsperoAI/.deps/native/ps5-payload-sdk -isystem /Users/anant/Workspace/ProsperoAI/.deps/native/ps5-payload-sdk/target/include/c++/v1 -isystem /Users/anant/Workspace/ProsperoAI/.deps/native/ps5-payload-sdk/target/include -fno-stack-protector -fno-plt -femulated-tls -ffreestanding -fno-builtin -fPIC -nostdlib -O2")
set(CMAKE_CXX_FLAGS "-target x86_64-sie-ps5 -isysroot /Users/anant/Workspace/ProsperoAI/.deps/native/ps5-payload-sdk -isystem /Users/anant/Workspace/ProsperoAI/.deps/native/ps5-payload-sdk/target/include/c++/v1 -isystem /Users/anant/Workspace/ProsperoAI/.deps/native/ps5-payload-sdk/target/include -fno-stack-protector -fno-plt -femulated-tls -ffreestanding -fexceptions -frtti -fPIC -nostdlib -O2")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
